var interfaceConfig = {
    CANVAS_EXTRA: 104,
    CANVAS_RADIUS: 7,
    SHADOW_COLOR: '#ffffff',
    INITIAL_TOOLBAR_TIMEOUT: 200000,
    TOOLBAR_TIMEOUT: 400000,
    DEFAULT_REMOTE_DISPLAY_NAME: "Watcher",
    DEFAULT_DOMINANT_SPEAKER_DISPLAY_NAME: "Performer",
    DEFAULT_LOCAL_DISPLAY_NAME: "me",
    SHOW_JITSI_WATERMARK: false,
    JITSI_WATERMARK_LINK: "http://www.camxcam.net",
    SHOW_BRAND_WATERMARK: false,
    BRAND_WATERMARK_LINK: "",
    SHOW_POWERED_BY: false,
    GENERATE_ROOMNAMES_ON_WELCOME_PAGE: false,
    APP_NAME: "Jitsi Meet",
    INVITATION_POWERED_BY: true,
    ACTIVE_SPEAKER_AVATAR_SIZE: 100
};
